#Generate Peer Review File
name: SimDiff Peer Review File Generation

on:
  push:
    branches:
      - '**'   # all branches
  pull_request:

jobs:
  simdiff_peer_review:
    name: Generate SimDiff Peer Review File
    runs-on: self-hosted   # your Windows self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  

 
      # ============ Invoke SimDiff ===============
      - name: Run SimDiff comparison
        shell: 'powershell -ExecutionPolicy Bypass -File {0}'
        run: |
          Write-Host "Comparing with SimDiff..."
          python .\diff.py reports HEAD~1 HEAD

      # ============ Publish Artifact ===============
      - name: Upload SimDiff Peer Review File
        uses: actions/upload-artifact@v4
        with:
          name: simdiff peer review files
          path: reports
